# Generated by Django 3.0.4 on 2020-07-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('imageone', models.ImageField(blank=True, upload_to='media')),
                ('imagetwo', models.ImageField(blank=True, upload_to='media')),
                ('technologies', models.TextField()),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
