# Generated by Django 3.0.4 on 2020-07-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='imageone',
            field=models.ImageField(blank=True, upload_to='projects/images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='imagetwo',
            field=models.ImageField(blank=True, upload_to='projects/images'),
        ),
    ]
